Creating a function to receive a covariance matrix and return a Kriging matrix C

In [9]:
import numpy as np

In [16]:
cov = np.array ([[10,14,6],
                 [23, 34,8],
                [55,7,9]])

In [17]:
cov

array([[10, 14,  6],
       [23, 34,  8],
       [55,  7,  9]])

In [37]:
def mat_c(cov):
    cov_shape = cov.shape
    C_shape = (cov_shape[0]+1, cov.shape[1]+1)
    C = np.ones(C_shape)
    C[C_shape[0]-1,C_shape[1]-1] = 0
    C[:-1,:-1] = cov
    return C

In [42]:
C = mat_c(cov)

In [43]:
for n, i in enumerate (C):
    print ('elemento', n, 'eh', i)

elemento 0 eh [10. 14.  6.  1.]
elemento 1 eh [23. 34.  8.  1.]
elemento 2 eh [55.  7.  9.  1.]
elemento 3 eh [1. 1. 1. 0.]


In [57]:
exe1 = np.linspace(1,10,10)
exe2 = np.linspace(11,20,10)



array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [61]:
emp = np.vstack((exe1,exe2))
emp
emp.shape

(2, 10)

In [72]:
zero = np.insert(emp,2,0, axis=0)
zero

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [75]:
uns = np.insert(zero,2,1,axis=0)
uns

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [109]:
array = np.arange(0,10,1)
lista = array.tolist()


Operações

In [110]:
lista*3



[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9]

In [111]:
array*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [112]:
array+3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [113]:
new_a = np.arange(0,19,2)
new_a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [114]:
new_a+array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [117]:
a_bi = np.array([[2,3,4],[5,6,7]])

In [118]:
a_bi

array([[2, 3, 4],
       [5, 6, 7]])

In [119]:
exp = np.exp(a_bi)
exp

array([[   7.3890561 ,   20.08553692,   54.59815003],
       [ 148.4131591 ,  403.42879349, 1096.63315843]])

In [121]:
sum_col = np.sum(a_bi, axis=1)
sum_col

array([ 9, 18])

In [122]:
sum_line = np.sum(a_bi, axis=0)
sum_line

array([ 7,  9, 11])

Vetores de Minério de Ferro

In [123]:
teor_ferro = np.array([44, 35, 19, 58, 62, 23, 2, 69, 42, 73,
  8, 20, 41, 87, 95, 23, 12, 65, 80, 55])
teor_ferro

array([44, 35, 19, 58, 62, 23,  2, 69, 42, 73,  8, 20, 41, 87, 95, 23, 12,
       65, 80, 55])

In [125]:
var = np.var(teor_ferro)
var

725.0275

In [126]:
mean = np.mean(teor_ferro)
mean

45.65

In [128]:
filtro = teor_ferro > mean
teor_ferro[filtro]

array([58, 62, 69, 73, 87, 95, 65, 80, 55])

In [133]:
p80 = np.percentile(teor_ferro,80)
capping = np.where(teor_ferro > p80, p80, teor_ferro)
capping


array([44. , 35. , 19. , 58. , 62. , 23. ,  2. , 69. , 42. , 69.8,  8. ,
       20. , 41. , 69.8, 69.8, 23. , 12. , 65. , 69.8, 55. ])

Calcule o valor krigado no ponto O

In [163]:
def dist(p1, p2):
    return np.sqrt((p1[0]-p2[0])**2 + (p1[1]-p2[1])**2)

def covariance(h):
    return np.exp(-(h/18)**2)


dist_mat = np.array([[dist((3,10),(3,10)), dist((3,10),(-2,5)), dist((3,10),(4,-5))],
                     [dist((3,10),(-2,5)), dist((-2,5),(-2,5)), dist((4,-5),(-2,5))],
                     [dist((4,-5),(3,10)), dist((4,-5),(-2,5)), dist((4,-5),(4,-5))]]) 


dist_vert = np.array([[dist((3,10),(0,0)), dist((0,0),(-2,5)), dist((0,0),(4,-5))]])
                   
cov_mat = covariance(dist_mat)

cov_vec = covariance(dist_vert)

In [164]:
def mat_c (cov):
    cov_shape = cov.shape
    C_shape =(cov_shape[0]+1, cov_shape[1]+1)
    C = np.ones(C_shapes)
    C[C_shape[0]-1, C_shape[1]-1] = 0
    C[:-1,:-1] = cov
    
    
C = mat_c(cov_mat)



NameError: name 'C_shapes' is not defined

In [165]:
D = np.append(cov_vec, 1)

c_inv = np.linalg.inv(C)

W = c_inv @ D

grade = 53*W[0]+ 40*W[1]+ 32*W[1]

grade

LinAlgError: 0-dimensional array given. Array must be at least two-dimensional

Exercício eleições

In [178]:
#def eleicoes (candidatos, num_votos):
    #votos = np.random.choice(candidatos, num_votos)
    #print (votos)
   # for c in candidatos:
     #   num_votos = votos.tolist().count(c)
    #    resultado[c]=num_votos
   # return resultado

In [179]:
#candidatos=['Led','Pink','AC','Stones','Deep']
#n= 10000

In [181]:
#eleicoes(candidatos, n)

Exercício banco de dados sinteticos

In [182]:
import itertools

In [226]:
x_range = np.linspace(0, 100, 10)
y_range = np.linspace(0, 100, 10)

teores = np.random.randn(100)
teores_2 = teores.reshape(100,1)

coord = []

for x,y in itertools.product(x_range,y_range):
    coord.append([x,y])


In [227]:
coordenadas = np.array(coord)

dataset = np.hstack((coordenadas, teores_2))

In [228]:
dataset.shape

(100, 3)

In [229]:
x_range

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])